    - name: Install Java JDK with win_package
      win_package:
        path: https://download.oracle.com/java/18/latest/jdk-18_windows-x64_bin.exe
        state: present

    - name: Set Java_home
      win_environment:
        state: present
        name: JAVA_HOME
        value: 'C:\Program Files\Java\jdk-"{{version}}"'
        level: machine

    - name: Add Java to path
      win_path:
        elements:
          - 'C:\Program Files\Java\jdk-"{{version}}"\bin'    